// Code generated by generate.go. DO NOT EDIT.

package customized

import (
	"honnef.co/go/tools/analysis/lint"
	"honnef.co/go/tools/customized/cs1000"
	"honnef.co/go/tools/customized/cs1001"
)

var Analyzers = []*lint.Analyzer{
	cs1000.SCAnalyzer,
	cs1001.SCAnalyzer,
}
